--- a/.github/workflows/build_coverage.yaml
+++ b/.github/workflows/build_coverage.yaml
@@ -69,5 +69,4 @@
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           format: cobertura
-          files:
-            - coverage/cobertura-coverage.xml
+          files: coverage/cobertura-coverage.xml